use std::ops::Range;
use std::sync::Arc;

use vulkano::buffer::{Buffer, BufferCreateInfo, BufferUsage};
use vulkano::command_buffer::{
    BlitImageInfo, CopyBufferToImageInfo, ImageBlit, RecordingCommandBuffer,
};
use vulkano::format::{Format, FormatFeatures};
use vulkano::image::sampler::Filter;
use vulkano::image::view::ImageView;
use vulkano::image::{
    Image, ImageAspects, ImageCreateInfo, ImageLayout, ImageSubresourceLayers,
    ImageSubresourceRange, ImageType, ImageUsage, max_mip_levels, mip_level_extent,
};
use vulkano::memory::allocator::{AllocationCreateInfo, MemoryTypeFilter};

use super::context::VkContext;
use super::record;

pub(super) enum MipPolicy {
    /// One level. For data textures (noise, LUTs) and 1x1 fallbacks.
    None,
    /// Full chain, generated by a blit chain at upload.
    Generate,
}

/// A run of mip levels, all layers.
fn level_range(image: &Arc<Image>, mip_levels: Range<u32>) -> ImageSubresourceRange {
    ImageSubresourceRange {
        aspects: ImageAspects::COLOR,
        mip_levels,
        array_layers: 0..image.array_layers(),
    }
}

/// Fills mip levels 1.. by successively halving level 0 with a linear blit.
/// Assumes level 0 is already populated and the image carries `TRANSFER_SRC`.
///
/// Every level is written as a blit destination and then read as the next
/// blit's source, so each iteration needs two dependencies the auto-synchronised
/// path used to derive: level `n-1` must finish being written before it is read,
/// and it must be in `TransferSrcOptimal` when it is. The whole image is already
/// in `TransferDstOptimal` on entry.
fn generate_mips(recording: &mut RecordingCommandBuffer, image: &Arc<Image>) {
    let base = image.extent();
    let source_layers = image.subresource_layers();
    let aspects = source_layers.aspects;

    for level_index in 1..image.mip_levels() {
        let src_extent = mip_level_extent(base, level_index - 1).unwrap();
        let dst_extent = mip_level_extent(base, level_index).unwrap();

        let region = ImageBlit {
            src_subresource: ImageSubresourceLayers {
                aspects,
                mip_level: level_index - 1,
                array_layers: 0..1,
            },
            src_offsets: [[0, 0, 0], src_extent],
            dst_subresource: ImageSubresourceLayers {
                aspects,
                mip_level: level_index,
                array_layers: 0..1,
            },
            dst_offsets: [[0, 0, 0], dst_extent],
            ..Default::default()
        };

        record::image_barrier(
            recording,
            record::transfer_dst_to_src(image.clone(), level_range(image, level_index - 1..level_index)),
        );

        // SAFETY: the barrier above orders this blit's read of `level - 1`
        // after the write that produced it, and has put that level in the
        // source layout `BlitImageInfo::images` names; the destination level
        // has been in `TransferDstOptimal` since the pre-copy transition and
        // no earlier command in this buffer has touched it.
        unsafe {
            recording.blit_image(&BlitImageInfo {
                regions: vec![region].into(),
                filter: Filter::Linear,
                ..BlitImageInfo::images(image.clone(), image.clone())
            })
        }
        .expect("invalid mip blit");
    }
}

// `format` chooses how the shader interprets the bytes (e.g. `R8G8B8A8_SRGB`
// for color, `R8G8B8A8_UNORM` for data maps).
pub(super) fn upload_texture(
    ctx: &VkContext,
    pixels: &[u8],
    extent: [u32; 2],
    format: Format,
    mips: MipPolicy,
) -> Arc<ImageView> {
    let physical = ctx.device.physical_device();

    let blittable = physical
        .format_properties(format)
        .unwrap()
        .optimal_tiling_features
        .contains(
            FormatFeatures::BLIT_SRC
                | FormatFeatures::BLIT_DST
                | FormatFeatures::SAMPLED_IMAGE_FILTER_LINEAR,
        );

    let full_chain = max_mip_levels([extent[0], extent[1], 1]);

    let mip_levels = match mips {
        MipPolicy::Generate if blittable => full_chain,
        _ => 1,
    };

    let staging = Buffer::from_iter(
        ctx.memory_allocator.clone(),
        BufferCreateInfo {
            usage: BufferUsage::TRANSFER_SRC,
            ..Default::default()
        },
        AllocationCreateInfo {
            memory_type_filter: MemoryTypeFilter::PREFER_HOST
                | MemoryTypeFilter::HOST_SEQUENTIAL_WRITE,
            ..Default::default()
        },
        pixels.iter().copied(),
    )
    .expect("failed to allocate texture staging buffer");

    let image = Image::new(
        ctx.memory_allocator.clone(),
        ImageCreateInfo {
            image_type: ImageType::Dim2d,
            format,
            extent: [extent[0], extent[1], 1],
            mip_levels,
            usage: ImageUsage::TRANSFER_DST | ImageUsage::SAMPLED | ImageUsage::TRANSFER_SRC,
            ..Default::default()
        },
        AllocationCreateInfo {
            memory_type_filter: MemoryTypeFilter::PREFER_DEVICE,
            ..Default::default()
        },
    )
    .expect("failed to create texture image");

    let copy = CopyBufferToImageInfo::buffer_image(staging, image.clone());

    record::submit_one_shot(ctx, |recording| {
        // Fresh out of `Image::new`, so every level is `Undefined` and there is
        // nothing to preserve — one barrier covers the whole chain, and the
        // levels the copy does not write are the ones the blits below will.
        record::image_barrier(
            recording,
            record::to_transfer_dst(
                image.clone(),
                record::whole_image(&image),
                ImageLayout::Undefined,
            ),
        );

        // SAFETY: the transition above put level 0 in the layout
        // `CopyBufferToImageInfo::buffer_image` names, and the staging buffer is
        // written and never touched again before `submit_one_shot` returns.
        unsafe { recording.copy_buffer_to_image(&copy) }.expect("invalid texture copy");

        if mip_levels > 1 {
            generate_mips(recording, &image);
        }

        // What the chain left behind: every level but the last was read as a
        // blit source, the last was only ever written. With no chain, level 0 is
        // still the copy's destination.
        if mip_levels > 1 {
            record::image_barrier(
                recording,
                record::to_shader_read(
                    image.clone(),
                    level_range(&image, 0..mip_levels - 1),
                    ImageLayout::TransferSrcOptimal,
                ),
            );
        }
        record::image_barrier(
            recording,
            record::to_shader_read(
                image.clone(),
                level_range(&image, mip_levels - 1..mip_levels),
                ImageLayout::TransferDstOptimal,
            ),
        );
    });

    ImageView::new_default(image).expect("failed to create texture image view")
}
